categories:
  - title: '🚀 Features'
    labels:
      - 'feat'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'revert'
  - title: '⚡ Performance'
    labels:
      - 'perf'
  - title: '🔧 Maintenance'
    labels:
      - 'build'
      - 'style'
      - 'docs'
      - 'refactor'
      - 'test'
      - 'chore'
      - 'ci'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
template: |
  ## What's Changed

  $CHANGES
