cargo-features = [ "edition2021" ]

[package]
name = "backend"
authors = ["Rob Wagner <rob@sombia.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.0-rc.1", features = ["json", "secrets"] }
rocket_cors = { git = "https://github.com/lawliet89/rocket_cors", branch = "master" }
relative-path = "1.5.0"
sqlx = { version = "0.5.9", features = [
    "runtime-tokio-rustls",
    "postgres",
] }
dotenv = "0.15.0"
rocket-pg-sqlx = { version = "0.1", git = "https://github.com/robertwayne/rocket-pg-sqlx" }